<?php

namespace ContainerUT4XX63;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotifier_Channel_DesktopService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'notifier.channel.desktop' shared service.
     *
     * @return \Symfony\Component\Notifier\Channel\DesktopChannel
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/notifier/Channel/ChannelInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/notifier/Channel/AbstractChannel.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/notifier/Channel/DesktopChannel.php';

        return $container->privates['notifier.channel.desktop'] = new \Symfony\Component\Notifier\Channel\DesktopChannel(($container->privates['texter.transports'] ?? $container->load('getTexter_TransportsService')), NULL);
    }
}
