<?php

namespace ContainerUT4XX63;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUsersControllergetUserOrdersService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.13jsxUt.App\Controller\UsersController::getUserOrders()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.13jsxUt.App\\Controller\\UsersController::getUserOrders()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'orderService' => ['privates', 'App\\Service\\Order\\OrderService', 'getOrderServiceService', true],
            'serializer' => ['privates', 'serializer', 'getSerializerService', false],
        ], [
            'orderService' => 'App\\Service\\Order\\OrderService',
            'serializer' => '?',
        ]))->withContext('App\\Controller\\UsersController::getUserOrders()', $container);
    }
}
