<?php

namespace ContainerRsUbhFo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrdersControllerupdateStatusService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UTPSXD3.App\Controller\OrdersController::updateStatus()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UTPSXD3.App\\Controller\\OrdersController::updateStatus()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'order' => ['privates', '.errored..service_locator.UTPSXD3.App\\Entity\\Order', NULL, 'Cannot autowire service ".service_locator.UTPSXD3": it needs an instance of "App\\Entity\\Order" but this type has been excluded in "config/services.yaml".'],
            'orderService' => ['privates', 'App\\Service\\Order\\OrderService', 'getOrderServiceService', true],
            'eventDispatcher' => ['services', 'event_dispatcher', 'getEventDispatcherService', false],
        ], [
            'order' => 'App\\Entity\\Order',
            'orderService' => 'App\\Service\\Order\\OrderService',
            'eventDispatcher' => '?',
        ]))->withContext('App\\Controller\\OrdersController::updateStatus()', $container);
    }
}
