<?php

namespace ContainerRsUbhFo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrdersControllercreateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.J8v1vv1.App\Controller\OrdersController::create()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.J8v1vv1.App\\Controller\\OrdersController::create()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'serializer' => ['privates', 'serializer', 'getSerializerService', false],
            'orderService' => ['privates', 'App\\Service\\Order\\OrderService', 'getOrderServiceService', true],
        ], [
            'serializer' => '?',
            'orderService' => 'App\\Service\\Order\\OrderService',
        ]))->withContext('App\\Controller\\OrdersController::create()', $container);
    }
}
