<?php

namespace ContainerRsUbhFo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUsersControllerstoreService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.u5ZbMAh.App\Controller\UsersController::store()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.u5ZbMAh.App\\Controller\\UsersController::store()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'serializer' => ['privates', 'serializer', 'getSerializerService', false],
            'userService' => ['privates', 'App\\Service\\User\\UserService', 'getUserServiceService', true],
        ], [
            'serializer' => '?',
            'userService' => 'App\\Service\\User\\UserService',
        ]))->withContext('App\\Controller\\UsersController::store()', $container);
    }
}
