<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUT4XX63\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUT4XX63/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUT4XX63.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUT4XX63\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUT4XX63\App_KernelDevDebugContainer([
    'container.build_hash' => 'UT4XX63',
    'container.build_id' => '4c71b35f',
    'container.build_time' => 1734383168,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUT4XX63');
